### ISSUE TITLE
 I need to put this api to work

### ISSUE THREAD

**Issue by nexuskillerx** [chrisbutler/tls#4]
I'm having trouble putting this api to work...

can you help me? 

urgent...

**Comment by nexuskillerx** [comment]
W20210122-12:42:34.662(-3)? (STDERR) C:\Users\BAIA08\AppData\Local\.meteor\packages\meteor-tool\2.0.0\mt-os.windows.x86_64\dev_bundle\server-lib\node_modules\fibers\future.js:280
W20210122-12:42:34.663(-3)? (STDERR)                                            throw(ex);
W20210122-12:42:34.663(-3)? (STDERR)                                            ^
W20210122-12:42:34.664(-3)? (STDERR) 
W20210122-12:42:34.671(-3)? (STDERR) ReferenceError: connect is not defined
W20210122-12:42:34.671(-3)? (STDERR)     at packages\chrisbutler_tls.js:22:8
W20210122-12:42:34.672(-3)? (STDERR)     at packages\chrisbutler_tls.js:30:4
W20210122-12:42:34.673(-3)? (STDERR)     at packages\chrisbutler_tls.js:352:3
W20210122-12:42:34.673(-3)? (STDERR)     at C:\Users\BAIA08\Desktop\meteor api\pack\.meteor\local\build\programs\server\boot.js:401:38
W20210122-12:42:34.674(-3)? (STDERR)     at Array.forEach (<anonymous>)
W20210122-12:42:34.674(-3)? (STDERR)     at C:\Users\BAIA08\Desktop\meteor api\pack\.meteor\local\build\programs\server\boot.js:226:21
W20210122-12:42:34.675(-3)? (STDERR)     at C:\Users\BAIA08\Desktop\meteor api\pack\.meteor\local\build\programs\server\boot.js:464:7
W20210122-12:42:34.675(-3)? (STDERR)     at Function.run (C:\Users\BAIA08\Desktop\meteor api\pack\.meteor\local\build\programs\server\profile.js:280:14)
W20210122-12:42:34.675(-3)? (STDERR)     at C:\Users\BAIA08\Desktop\meteor api\pack\.meteor\local\build\programs\server\boot.js:463:13
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
=> Modified -- restarting.
W20210122-12:42:47.885(-3)? (STDERR) C:\Users\BAIA08\AppData\Local\.meteor\packages\meteor-tool\2.0.0\mt-os.windows.x86_64\dev_bundle\server-lib\node_modules\fibers\future.js:280
W20210122-12:42:47.885(-3)? (STDERR)                                            throw(ex);
W20210122-12:42:47.886(-3)? (STDERR)                                            ^
W20210122-12:42:47.887(-3)? (STDERR) 
W20210122-12:42:47.887(-3)? (STDERR) TypeError: TLS.connect is not a constructor
W20210122-12:42:47.887(-3)? (STDERR)     at packages\chrisbutler_tls.js:24:13
W20210122-12:42:47.888(-3)? (STDERR)     at packages\chrisbutler_tls.js:30:4
W20210122-12:42:47.888(-3)? (STDERR)     at packages\chrisbutler_tls.js:352:3
W20210122-12:42:47.888(-3)? (STDERR)     at C:\Users\BAIA08\Desktop\meteor api\pack\.meteor\local\build\programs\server\boot.js:401:38
W20210122-12:42:47.889(-3)? (STDERR)     at Array.forEach (<anonymous>)
W20210122-12:42:47.898(-3)? (STDERR)     at C:\Users\BAIA08\Desktop\meteor api\pack\.meteor\local\build\programs\server\boot.js:226:21
W20210122-12:42:47.899(-3)? (STDERR)     at C:\Users\BAIA08\Desktop\meteor api\pack\.meteor\local\build\programs\server\boot.js:464:7
W20210122-12:42:47.899(-3)? (STDERR)     at Function.run (C:\Users\BAIA08\Desktop\meteor api\pack\.meteor\local\build\programs\server\profile.js:280:14)
W20210122-12:42:47.901(-3)? (STDERR)     at C:\Users\BAIA08\Desktop\meteor api\pack\.meteor\local\build\programs\server\boot.js:463:13
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.

**Comment by nexuskillerx** [comment]
W20210122-12:42:47.887(-3)? (STDERR) TypeError: TLS.connect is not a constructor

**Comment by nexuskillerx** [comment]
now I'm having this problem:

I20210123-09:28:48.523(-3)? 2021-01-23 09:28:48.520 info:  [tls:api]  localhost connected (200)
I20210123-09:28:48.525(-3)? 2021-01-23 09:28:48.525 info:  [tls:api]  localhost disconnected (15ms)
I20210123-09:28:48.526(-3)? 2021-01-23 09:28:48.525 info:  [tls:api]  localhost closed ([47] err: false) (15ms)
W20210123-09:28:48.529(-3)? (STDERR) C:\Users\BAIA08\AppData\Local\.meteor\packages\meteor-tool\2.0.0\mt-os.windows.x86_64\dev_bundle\server-lib\node_modules\fibers\future.js:280
W20210123-09:28:48.537(-3)? (STDERR)                                            throw(ex);
W20210123-09:28:48.539(-3)? (STDERR)                                            ^
W20210123-09:28:48.539(-3)? (STDERR) 
W20210123-09:28:48.540(-3)? (STDERR) TypeError: Cannot read property 'time' of undefined
W20210123-09:28:48.540(-3)? (STDERR)     at TLS.getTankNames (packages\chrisbutler_tls.js:202:27)
W20210123-09:28:48.540(-3)? (STDERR)     at new TLS (packages\chrisbutler_tls.js:185:25)
W20210123-09:28:48.541(-3)? (STDERR)     at module (server/main.js:1:13)
W20210123-09:28:48.541(-3)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:336:7)
W20210123-09:28:48.542(-3)? (STDERR)     at Module.require (packages\modules-runtime.js:238:14)
W20210123-09:28:48.542(-3)? (STDERR)     at require (packages\modules-runtime.js:258:21)
W20210123-09:28:48.543(-3)? (STDERR)     at C:\Users\BAIA08\Desktop\meteor api\pack\.meteor\local\build\programs\server\app\app.js:21:1
W20210123-09:28:48.543(-3)? (STDERR)     at C:\Users\BAIA08\Desktop\meteor api\pack\.meteor\local\build\programs\server\boot.js:401:38
W20210123-09:28:48.543(-3)? (STDERR)     at Array.forEach (<anonymous>)
W20210123-09:28:48.544(-3)? (STDERR)     at C:\Users\BAIA08\Desktop\meteor api\pack\.meteor\local\build\programs\server\boot.js:226:21
W20210123-09:28:48.544(-3)? (STDERR)     at C:\Users\BAIA08\Desktop\meteor api\pack\.meteor\local\build\programs\server\boot.js:464:7
W20210123-09:28:48.544(-3)? (STDERR)     at Function.run (C:\Users\BAIA08\Desktop\meteor api\pack\.meteor\local\build\programs\server\profile.js:280:14)
W20210123-09:28:48.545(-3)? (STDERR)     at C:\Users\BAIA08\Desktop\meteor api\pack\.meteor\local\build\programs\server\boot.js:463:13
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
